serverConfig:
  # ipAddress: 192.168.0.1 # ????
  # ipaddress: 192.168.0.1
  # IPADDRESS: 192.168.0.1
  ip-address: 192.168.0.1 # ????????????
  # ip_address: 192.168.0.1 # ?????
  # ip-address: 192.168.0.1 # ?????
  # IP_ADDRESS: 192.168.0.1 # ????
  # ip_Add_rEss: 192.168.0.1
  # ipaddress: 192.168.0.1
  port: 8888
  timeout: 270
  dataSize: 10

datasource:
  driverClassName: com.mysql.cj.jdbc.Driver123
  # ???????????????8???????????87
  # ?????????????????
  # password: 0127
  password: "123456"
