#debug: true
logging:
  # 设置分组
  group:
    ebank: top.Elsa.controller, top.Elsa.service, top.Elsa.mapper
    iservice: com.alibaba
  level:
    root: info
    # 设置某个包的日志级别
    # top.jacktgq.controller: debug
    # 设置分组，对组设置级别
    ebank: warn
  # 设置日志输出的模板格式
  pattern:
    # console: "%d - %m %n"
    # %d：日期时间
    # %p：日志级别
    # %5p：日志级别占5个字符
    # %clr：颜色
    # %16t：线程名占16个字符
    # %c：程序包名
    # %40c：程序包名占40位，默认居中
    # %-40c：程序报名占40位并且左对齐
    # %-40.40c：程序报名占40位并且左对齐，超过40的截掉
    # %clr(%-40.40c){cyan}：程序报名占40位并且左对齐，超过40的截掉，指定颜色为青色
    # %m：消息
    # %n：换行
    # console: "%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 4KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log